//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRoomByType
    {
        public int ID { get; set; }
        public int IDCustomer { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public int Suite { get; set; }
        public int Standard { get; set; }
        public int Superior { get; set; }
        public bool BookingStatus { get; set; }
    }
}
